<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE global [
        <!ELEMENT global (trace)*>
        <!ELEMENT trace (time|meth|data|part)*>
        <!ELEMENT time (#PCDATA)>
        <!ELEMENT meth (#PCDATA)>
        <!ELEMENT data (budget|contracts|men|heading|action|parameters|status|cost|extras)*>
        <!ELEMENT budget (#PCDATA)>
        <!ELEMENT contracts (amount|resource)*>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT resource (#PCDATA)>
        <!ELEMENT men (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT part (#PCDATA)>
        <!ELEMENT action (#PCDATA)>
        <!ELEMENT parameters (direction|creek|people|resource)*>
        <!ELEMENT direction (#PCDATA)>
        <!ELEMENT status (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT extras (range|found|biomes|creeks|resources|pois|amount|altitude)*>
        <!ELEMENT range (#PCDATA)>
        <!ELEMENT found (#PCDATA)>
        <!ELEMENT biomes (#PCDATA)>
        <!ELEMENT creeks (#PCDATA)>
        <!ELEMENT creek (#PCDATA)>
        <!ELEMENT people (#PCDATA)>
        <!ELEMENT resources (amount|resource|cond)*>
        <!ELEMENT cond (#PCDATA)>
        <!ELEMENT pois (id|kind)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT kind (#PCDATA)>
        <!ELEMENT altitude (#PCDATA)>
        ]>
<global>
<trace><time>1451849508420</time><meth>initialize</meth><data><budget>10000</budget><contracts><amount>100</amount><resource>GLASS</resource></contracts><contracts><amount>5000</amount><resource>WOOD</resource></contracts><contracts><amount>80</amount><resource>FLOWER</resource></contracts><men>25</men><heading>S</heading></data><part>Engine</part></trace><trace><time>1451849508438</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508438</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras><range>52</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508440</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508440</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><range>52</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508441</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>W</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508441</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><range>0</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508442</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508443</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508443</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>N</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508443</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><range>1</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508443</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508444</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><range>51</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508444</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508445</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras><range>51</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508445</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508445</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508446</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508446</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><range>50</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508446</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508447</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras><range>50</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508448</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508448</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508448</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>N</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508448</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras><range>3</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508448</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508448</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><range>19</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508449</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508449</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><range>20</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508449</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508449</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508450</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508450</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><range>17</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508450</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508450</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><range>15</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508451</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508451</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508451</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>N</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508451</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><range>5</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508451</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508451</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><range>16</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508451</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508452</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><range>5</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508452</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508452</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508452</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508452</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><range>15</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508453</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508453</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><range>3</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508453</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508453</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508453</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>N</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508453</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras><range>7</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508453</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508454</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><range>13</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508454</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508454</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><range>2</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508454</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508454</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508454</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508455</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><range>12</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508455</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508455</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><range>0</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508455</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508455</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508455</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>N</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508455</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><range>9</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508455</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><range>11</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><range>0</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><range>1</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><range>0</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508456</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508457</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>N</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508457</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras><range>11</range><found>OUT_OF_RANGE</found></extras></data><part>Engine</part></trace><trace><time>1451849508457</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508457</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><range>0</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508457</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508457</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras><range>0</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508457</time><meth>takeDecision</meth><data><action>heading</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508457</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508457</time><meth>takeDecision</meth><data><action>echo</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508458</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><range>0</range><found>GROUND</found></extras></data><part>Engine</part></trace><trace><time>1451849508458</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508458</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><biomes>BEACH</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508460</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508460</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><biomes>BEACH</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508460</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508460</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508460</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508460</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><biomes>BEACH</biomes><biomes>SHRUBLAND</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508460</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508460</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><biomes>TROPICAL_SEASONAL_FOREST</biomes><biomes>SHRUBLAND</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><biomes>SHRUBLAND</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><biomes>SHRUBLAND</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508461</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508462</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508462</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras><biomes>TROPICAL_SEASONAL_FOREST</biomes><biomes>SHRUBLAND</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508462</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508462</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><biomes>LAKE</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><biomes>LAKE</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508463</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><biomes>LAKE</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><biomes>LAKE</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><status>OK</status><cost>2</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras><biomes>LAKE</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><status>OK</status><cost>5</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508464</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><biomes>TROPICAL_RAIN_FOREST</biomes><biomes>LAKE</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508465</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508465</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508465</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508465</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><biomes>TROPICAL_RAIN_FOREST</biomes><biomes>MANGROVE</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508465</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508465</time><meth>takeDecision</meth><data><status>OK</status><cost>2</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508465</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508465</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras><biomes>MANGROVE</biomes></extras></data><part>Engine</part></trace><trace><time>1451849508466</time><meth>takeDecision</meth><data><action>fly</action></data><part>Explorer</part></trace><trace><time>1451849508466</time><meth>takeDecision</meth><data><status>OK</status><cost>3</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508466</time><meth>takeDecision</meth><data><action>scan</action></data><part>Explorer</part></trace><trace><time>1451849508466</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><biomes>MANGROVE</biomes><creeks>1c924697-6a61-47d6-936f-3f32eca50af1</creeks></extras></data><part>Engine</part></trace><trace><time>1451849508466</time><meth>takeDecision</meth><data><action>land</action><parameters><creek>1c924697-6a61-47d6-936f-3f32eca50af1</creek><people>4</people></parameters></data><part>Explorer</part></trace><trace><time>1451849508466</time><meth>takeDecision</meth><data><status>OK</status><cost>18</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508469</time><meth>takeDecision</meth><data><action>explore</action></data><part>Explorer</part></trace><trace><time>1451849508470</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><resources><amount>LOW</amount><resource>WOOD</resource><cond>FAIR</cond></resources><resources><amount>LOW</amount><resource>FISH</resource><cond>FAIR</cond></resources><resources><amount>HIGH</amount><resource>FLOWER</resource><cond>FAIR</cond></resources><pois><id>1c924697-6a61-47d6-936f-3f32eca50af1</id><kind>Creek</kind></pois></extras></data><part>Engine</part></trace><trace><time>1451849508471</time><meth>takeDecision</meth><data><action>exploit</action><parameters><resource>FLOWER</resource></parameters></data><part>Explorer</part></trace><trace><time>1451849508471</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><amount>1</amount></extras></data><part>Engine</part></trace><trace><time>1451849508471</time><meth>takeDecision</meth><data><action>explore</action></data><part>Explorer</part></trace><trace><time>1451849508471</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><resources><amount>LOW</amount><resource>WOOD</resource><cond>FAIR</cond></resources><resources><amount>LOW</amount><resource>FISH</resource><cond>FAIR</cond></resources><resources><amount>LOW</amount><resource>FLOWER</resource><cond>FAIR</cond></resources><pois><id>1c924697-6a61-47d6-936f-3f32eca50af1</id><kind>Creek</kind></pois></extras></data><part>Engine</part></trace><trace><time>1451849508472</time><meth>takeDecision</meth><data><action>scout</action><parameters><direction>N</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508472</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><resources>FLOWER</resources><altitude>1</altitude></extras></data><part>Engine</part></trace><trace><time>1451849508472</time><meth>takeDecision</meth><data><action>scout</action><parameters><direction>S</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508472</time><meth>takeDecision</meth><data><status>OK</status><cost>8</cost><extras><resources>WOOD</resources><resources>FISH</resources><altitude>0</altitude></extras></data><part>Engine</part></trace><trace><time>1451849508472</time><meth>takeDecision</meth><data><action>scout</action><parameters><direction>E</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508472</time><meth>takeDecision</meth><data><status>OK</status><cost>6</cost><extras><resources>FISH</resources><resources>FLOWER</resources><altitude>0</altitude></extras></data><part>Engine</part></trace><trace><time>1451849508473</time><meth>takeDecision</meth><data><action>scout</action><parameters><direction>W</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508473</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras><resources>WOOD</resources><resources>FLOWER</resources><altitude>1</altitude></extras></data><part>Engine</part></trace><trace><time>1451849508473</time><meth>takeDecision</meth><data><action>move_to</action><parameters><direction>W</direction></parameters></data><part>Explorer</part></trace><trace><time>1451849508473</time><meth>takeDecision</meth><data><status>OK</status><cost>7</cost><extras></extras></data><part>Engine</part></trace><trace><time>1451849508473</time><meth>takeDecision</meth><data><action>explore</action></data><part>Explorer</part></trace><trace><time>1451849508473</time><meth>takeDecision</meth><data><status>OK</status><cost>4</cost><extras><resources><amount>LOW</amount><resource>WOOD</resource><cond>FAIR</cond></resources><resources><amount>HIGH</amount><resource>FLOWER</resource><cond>FAIR</cond></resources></extras></data><part>Engine</part></trace><trace><time>1451849508473</time><meth>takeDecision</meth><data><action>exploit</action><para